version: "3.9"
services:
  app:
    image: go-auth-id-app:latest
    ports:
      - "9090:9090"
    depends_on:
      - postgres-master
    volumes:
      - ./.env:/go/auth-id/.env
      # - ./env.local:/go/auth-id/env.local
    deploy:
      mode: global
      # placement:
      #   constraints:
      #     - "node.labels.TAG==my-swarm"
  postgres-master:
    env_file: .env
    image: postgres:15
    container_name: auth-id-postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ../auth-id-postgres-data:/var/lib/postgresql/data
      - ./migration:/opt/migration
    ports:
      - "5432:5432"
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 10s
    deploy:
      mode: global
      # update_config:
      #   parallelism: 1
      #   order: start-first
      #   failure_action: rollback
      #   delay: 10s
      # placement:
      #   constraints:
      #     - "node.labels.TAG==my-swarm"